version: '3'
services:
    authorization:
        image: "moviecruiserauth"
        ports:
            - "8081:80"
        links:
            - db
        environment:
            SQL_AUTH: "Data source=db;initial catalog=UserDb;User id=sa;Password=P@ssw0rd"
    backend:
        image: "moviecruiser"
        ports:
            - "8089:80"
        links:
            - db
            - authorization
        environment:
            SQL_MOVIE: "Data source=db;initial catalog=MoviesDb;User id=sa;Password=P@ssw0rd"
    frontend:
        image: "moveicruiserui"
        ports:
            - "4200:4200"
        links:
            - backend
    db:
        image: "microsoft/mssql-server-windows-express"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"